### GET Animals
GET http://localhost:8080/zoo/animals

### POST Animal
POST http://localhost:8080/zoo/animal
Content-Type: application/json

{
  "name": "MyDog",
  "weight": 30,
  "ageInYear": 10,
  "color": "Black",
  "gender": "male",
  "species": "Dog"
}

### Feed Animal by Id
PUT http://localhost:8080/zoo/feed/animal/624f3a82-b169-41d6-bd56-9b37c006d89e
Content-Type: application/json

{
  "foodWeight": 10.8
}

### DELETE Animal by Id
DELETE http://localhost:8080/zoo/animal/624f3a82-b169-41d6-bd56-9b37c006d89e

### Search Animals
POST http://localhost:8080/zoo/search/animals
Content-Type: application/json

{
  "searchCriteria" :
  {
    "key": "name",
    "value": "MyDog1"
  }
}
